name: OpenFaaS CI/CD Anush Bundel 2023BCS0005

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Start Docker
        run: sudo systemctl start docker

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install OpenFaaS
        run: |
          kubectl create namespace openfaas
          kubectl create namespace openfaas-fn

          helm repo add openfaas https://openfaas.github.io/faas-netes/
          helm repo update

          helm upgrade openfaas openfaas/openfaas \
            --install \
            --namespace openfaas \
            --set functionNamespace=openfaas-fn \
            --set generateBasicAuth=true

      - name: Wait for OpenFaaS
        run: kubectl rollout status deploy/gateway -n openfaas --timeout=120s

      - name: Get password
        run: |
          kubectl -n openfaas get secret basic-auth \
          -o jsonpath="{.data.basic-auth-password}" | base64 --decode > password.txt

      - name: Copy password to terraform
        run: cp password.txt terraform/password.txt

      - name: Port forward
        run: |
          kubectl port-forward svc/gateway -n openfaas 8080:8080 &
          sleep 10

      - name: Install faas-cli
        run: curl -sSL https://cli.openfaas.com | sudo sh

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          cat password.txt | faas-cli login --username admin --password-stdin
          terraform apply -auto-approve
          sleep 30

      - name: Terraform Destroy
        run: |
          cd terraform
          cat password.txt | faas-cli login --username admin --password-stdin
          terraform destroy -auto-approve
